"""add_company_and_sheet_metadata

Revision ID: 03216da8cc7a
Revises: 0a0de421ff66
Create Date: 2026-02-20 15:48:57.450189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03216da8cc7a'
down_revision: Union[str, Sequence[str], None] = '0a0de421ff66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('companies',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('owner_name', sa.String(), nullable=True),
    # sa.Column('address', sa.String(), nullable=True),
    # sa.Column('phone', sa.String(), nullable=True),
    # sa.Column('fax', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.Column('registration_number', sa.String(), nullable=True),
    # sa.Column('logo_image', sa.JSON(), nullable=True),
    # sa.Column('stamp_image', sa.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('companies', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_metadata', sa.JSON(), nullable=True))

    # with op.batch_alter_table('sales_orders', schema=None) as batch_op:
    #     batch_op.alter_column('status',
    #            existing_type=sa.VARCHAR(length=9),
    #            type_=sa.Enum('PENDING', 'CONFIRMED', 'PRODUCTION_COMPLETED', 'DELIVERY_COMPLETED', 'CANCELLED', name='orderstatus'),
    #            existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_column('sheet_metadata')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
