"""Add production_plan_item_id to PurchaseOrderItem

Revision ID: 1957ae59e6f1
Revises: 2f2def70d24a
Create Date: 2026-02-13 16:06:43.490027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1957ae59e6f1'
down_revision: Union[str, Sequence[str], None] = '2f2def70d24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_plan_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_purchase_order_items_production_plan_item_id_production_plan_items'), 'production_plan_items', ['production_plan_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_order_items_production_plan_item_id_production_plan_items'), type_='foreignkey')
        batch_op.drop_column('production_plan_item_id')

    # ### end Alembic commands ###
