"""Add production tables and cleanup sales

Revision ID: 2f2def70d24a
Revises: 8901abcdef23
Create Date: 2026-02-13 13:03:08.284172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2def70d24a'
down_revision: Union[str, Sequence[str], None] = '8901abcdef23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS production_plan_items")
    op.create_table('production_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(), nullable=True),
    sa.Column('work_center', sa.String(), nullable=True),
    sa.Column('estimated_time', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('worker_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='productionstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_plan_items_id'), ['id'], unique=False)

    # with op.batch_alter_table('estimate_items', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'estimates', ['estimate_id'], ['id'])

    # with op.batch_alter_table('estimates', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'partners', ['partner_id'], ['id'])

    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('plan_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_production_plans_order_id', 'sales_orders', ['order_id'], ['id'])
        batch_op.drop_column('sales_order_item_id')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # with op.batch_alter_table('products', schema=None) as batch_op:
    # ...

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_work_orders_plan_item_id', 'production_plan_items', ['plan_item_id'], ['id'])
        batch_op.drop_column('production_plan_id')
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('production_plan_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'production_plans', ['production_plan_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('plan_item_id')

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'partners', ['partner_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sales_orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_products_partner_id_partners_final'), 'partners', ['partner_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('sales_order_item_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sales_order_items', ['sales_order_item_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('plan_date')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'partners', ['partner_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('estimate_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'estimates', ['estimate_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('production_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_plan_items_id'))

    op.drop_table('production_plan_items')
    # ### end Alembic commands ###
