"""Add_course_type_override_to_ProductProcess

Revision ID: 32718ae85cd1
Revises: d370ccfbd1a7
Create Date: 2026-02-12 09:31:03.057947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32718ae85cd1'
down_revision: Union[str, Sequence[str], None] = 'd370ccfbd1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.drop_column('course_type')

    # ### end Alembic commands ###
