"""add sheet_metadata to production_plans

Revision ID: 4b46ce8e5ae1
Revises: 54c6aeb5f9d4
Create Date: 2026-02-23 08:39:24.815998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b46ce8e5ae1'
down_revision: Union[str, Sequence[str], None] = '54c6aeb5f9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_file', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sheet_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_column('sheet_metadata')
        batch_op.drop_column('attachment_file')
    # ### end Alembic commands ###
