"""add substitute_product_id to bom

Revision ID: a5c9b7d8e2f1
Revises: f5c0e2a40b9d
Create Date: 2026-04-14 17:57:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c9b7d8e2f1'
down_revision: Union[str, Sequence[str], None] = 'f5c0e2a40b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "bom" in tables:
        cols = [c["name"] for c in inspector.get_columns("bom")]
        if "substitute_product_id" not in cols:
            op.add_column('bom', sa.Column('substitute_product_id', sa.Integer(), sa.ForeignKey('products.id', ondelete='SET NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom', 'substitute_product_id')
    # ### end Alembic commands ###
