"""add_auth_permissions

Revision ID: a7f8e9d0c1b2
Revises: f5c0e2a40b9d
Create Date: 2026-03-27 01:50:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = 'a7f8e9d0c1b2'
down_revision: Union[str, Sequence[str], None] = 'f5c0e2a40b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('staff')]
    
    with op.batch_alter_table('staff', schema=None) as batch_op:
        if 'is_sysadmin' not in columns:
            batch_op.add_column(sa.Column('is_sysadmin', sa.Boolean(), nullable=True, server_default='0'))
        if 'can_access_external' not in columns:
            batch_op.add_column(sa.Column('can_access_external', sa.Boolean(), nullable=True, server_default='0'))
        if 'can_view_others' not in columns:
            batch_op.add_column(sa.Column('can_view_others', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('can_view_others')
        batch_op.drop_column('can_access_external')
        batch_op.drop_column('is_sysadmin')
    # ### end Alembic commands ###
