"""fresh_start_v2

Revision ID: bc5c56114d0c
Revises: 
Create Date: 2026-02-11 15:47:06.656000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5c56114d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_type', sa.String(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)

    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('partner_type', sa.Enum('CUSTOMER', 'SUPPLIER', 'SUBCONTRACTOR', 'BOTH', name='partnertype'), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('representative', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partners_name'), ['name'], unique=False)

    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processes_id'), ['id'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('inspection_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('check_item', sa.String(), nullable=False),
    sa.Column('spec_min', sa.Float(), nullable=True),
    sa.Column('spec_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_processes_id'), ['id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('drawing_file', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_id'), ['id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SHIPPED', name='orderstatus'), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('delivered_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_no'), ['order_no'], unique=True)

    op.create_table('product_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('estimated_time', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_processes_id'), ['id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_id'), ['id'], unique=False)

    op.create_table('production_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_plans_id'), ['id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_plan_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('good_quantity', sa.Integer(), nullable=True),
    sa.Column('bad_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_id'), ['id'], unique=False)

    op.create_table('inspection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('inspector_name', sa.String(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id')
    )
    with op.batch_alter_table('inspection_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_results_id'))

    op.drop_table('inspection_results')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_plans_id'))

    op.drop_table('production_plans')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_processes_id'))

    op.drop_table('product_processes')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))

    op.drop_table('orders')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_id'))

    op.drop_table('products')
    with op.batch_alter_table('inspection_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_processes_id'))

    op.drop_table('inspection_processes')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_id'))

    op.drop_table('staff')
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processes_id'))

    op.drop_table('processes')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_name'))
        batch_op.drop_index(batch_op.f('ix_partners_id'))

    op.drop_table('partners')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
