"""manual creation of missing tables and columns

Revision ID: d2235759113c
Revises: 5ba817148c30
Create Date: 2026-02-27 14:54:11.456993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2235759113c'
down_revision: Union[str, Sequence[str], None] = '5ba817148c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # 1. Create missing tables
    if 'measuring_instruments' not in tables:
        op.create_table('measuring_instruments',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('code', sa.String(), nullable=False),
            sa.Column('spec', sa.String(), nullable=True),
            sa.Column('serial_number', sa.String(), nullable=True),
            sa.Column('calibration_cycle_months', sa.Integer(), nullable=True),
            sa.Column('next_calibration_date', sa.Date(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_measuring_instruments_code'), 'measuring_instruments', ['code'], unique=False)
        op.create_index(op.f('ix_measuring_instruments_id'), 'measuring_instruments', ['id'], unique=False)

    if 'calibration_history' not in tables:
        op.create_table('calibration_history',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('instrument_id', sa.Integer(), nullable=True),
            sa.Column('calibration_date', sa.Date(), nullable=False),
            sa.Column('calibrator', sa.String(), nullable=True),
            sa.Column('result', sa.String(), nullable=True),
            sa.Column('certificate_no', sa.String(), nullable=True),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('attachment_file', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['instrument_id'], ['measuring_instruments.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_calibration_history_id'), 'calibration_history', ['id'], unique=False)

    if 'tool_repair_history' not in tables:
        op.create_table('tool_repair_history',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('instrument_id', sa.Integer(), nullable=True),
            sa.Column('repair_date', sa.Date(), nullable=False),
            sa.Column('repair_content', sa.Text(), nullable=False),
            sa.Column('repair_company', sa.String(), nullable=True),
            sa.Column('cost', sa.Integer(), nullable=True),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('attachment_file', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['instrument_id'], ['measuring_instruments.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tool_repair_history_id'), 'tool_repair_history', ['id'], unique=False)

    if 'work_logs' not in tables:
        op.create_table('work_logs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('work_date', sa.Date(), nullable=False),
            sa.Column('worker_id', sa.Integer(), nullable=True),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['worker_id'], ['staff.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_work_logs_id'), 'work_logs', ['id'], unique=False)

    if 'work_log_items' not in tables:
        op.create_table('work_log_items',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('work_log_id', sa.Integer(), nullable=False),
            sa.Column('plan_item_id', sa.Integer(), nullable=False),
            sa.Column('worker_id', sa.Integer(), nullable=True),
            sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
            sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
            sa.Column('good_quantity', sa.Integer(), nullable=True),
            sa.Column('bad_quantity', sa.Integer(), nullable=True),
            sa.Column('note', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['plan_item_id'], ['production_plan_items.id'], ),
            sa.ForeignKeyConstraint(['work_log_id'], ['work_logs.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['worker_id'], ['staff.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_work_log_items_id'), 'work_log_items', ['id'], unique=False)

    if 'equipment_repair_history' not in tables:
        op.create_table('equipment_repair_history',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('equipment_id', sa.Integer(), nullable=True),
            sa.Column('repair_date', sa.Date(), nullable=False),
            sa.Column('repair_content', sa.Text(), nullable=False),
            sa.Column('repair_company', sa.String(), nullable=True),
            sa.Column('cost', sa.Integer(), nullable=True),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('attachment_file', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_equipment_repair_history_id'), 'equipment_repair_history', ['id'], unique=False)

    # 2. Add missing columns with batch alter table
    if 'product_processes' in tables:
        cols = [c['name'] for c in inspector.get_columns('product_processes')]
        if 'cost' not in cols:
            with op.batch_alter_table('product_processes', schema=None) as batch_op:
                batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        
    if 'production_plan_items' in tables:
        cols = [c['name'] for c in inspector.get_columns('production_plan_items')]
        if 'cost' not in cols:
            with op.batch_alter_table('production_plan_items', schema=None) as batch_op:
                batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        
    if 'stock_productions' in tables:
        cols = [c['name'] for c in inspector.get_columns('stock_productions')]
        if 'partner_id' not in cols:
            with op.batch_alter_table('stock_productions', schema=None) as batch_op:
                batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
                try:
                    batch_op.create_foreign_key("fk_stock_productions_partner_id", "partners", ["partner_id"], ["id"])
                except Exception:
                    pass # Ignore if error is raised due to sqlite or existing constraint
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'stock_productions' in tables:
        cols = [c['name'] for c in inspector.get_columns('stock_productions')]
        if 'partner_id' in cols:
            with op.batch_alter_table('stock_productions', schema=None) as batch_op:
                try:
                    batch_op.drop_constraint("fk_stock_productions_partner_id", type_="foreignkey")
                except Exception:
                    pass
                batch_op.drop_column('partner_id')
        
    if 'production_plan_items' in tables:
        cols = [c['name'] for c in inspector.get_columns('production_plan_items')]
        if 'cost' in cols:
            with op.batch_alter_table('production_plan_items', schema=None) as batch_op:
                batch_op.drop_column('cost')

    if 'product_processes' in tables:
        cols = [c['name'] for c in inspector.get_columns('product_processes')]
        if 'cost' in cols:
            with op.batch_alter_table('product_processes', schema=None) as batch_op:
                batch_op.drop_column('cost')

    if 'equipment_repair_history' in tables:
        op.drop_index(op.f('ix_equipment_repair_history_id'), table_name='equipment_repair_history')
        op.drop_table('equipment_repair_history')
    
    if 'work_log_items' in tables:
        op.drop_index(op.f('ix_work_log_items_id'), table_name='work_log_items')
        op.drop_table('work_log_items')
    
    if 'work_logs' in tables:
        op.drop_index(op.f('ix_work_logs_id'), table_name='work_logs')
        op.drop_table('work_logs')
    
    if 'tool_repair_history' in tables:
        op.drop_index(op.f('ix_tool_repair_history_id'), table_name='tool_repair_history')
        op.drop_table('tool_repair_history')
    
    if 'calibration_history' in tables:
        op.drop_index(op.f('ix_calibration_history_id'), table_name='calibration_history')
        op.drop_table('calibration_history')
    
    if 'measuring_instruments' in tables:
        op.drop_index(op.f('ix_measuring_instruments_id'), table_name='measuring_instruments')
        op.drop_index(op.f('ix_measuring_instruments_code'), table_name='measuring_instruments')
        op.drop_table('measuring_instruments')
    # ### end Alembic commands ###
