"""Add_new_fields

Revision ID: d370ccfbd1a7
Revises: bc5c56114d0c
Create Date: 2026-02-12 09:12:47.865277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd370ccfbd1a7'
down_revision: Union[str, Sequence[str], None] = 'bc5c56114d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_type', sa.String(), nullable=True))

    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('equipment_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attachment_file', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_processes', schema=None) as batch_op:
        batch_op.drop_column('attachment_file')
        batch_op.drop_column('equipment_name')
        batch_op.drop_column('partner_name')

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('course_type')

    # ### end Alembic commands ###
