"""add partner_id to stock_productions

Revision ID: f3a2b1c0d9e8
Revises: ef3c2319e79b
Create Date: 2026-02-24 16:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3a2b1c0d9e8"
down_revision: Union[str, Sequence[str], None] = "ef3c2319e79b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_productions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("partner_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_stock_productions_partner_id", "partners", ["partner_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_productions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_stock_productions_partner_id", type_="foreignkey")
        batch_op.drop_column("partner_id")

    # ### end Alembic commands ###
