"""add reference to approval_documents

Revision ID: f5c0e2a40b9d
Revises: 35581743d96b
Create Date: 2026-03-15 23:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c0e2a40b9d'
down_revision: Union[str, Sequence[str], None] = 'b1d7d5f8a9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "approval_documents" in tables:
        cols = [c["name"] for c in inspector.get_columns("approval_documents")]
        if "reference_id" not in cols:
            op.add_column('approval_documents', sa.Column('reference_id', sa.Integer(), nullable=True))
        if "reference_type" not in cols:
            op.add_column('approval_documents', sa.Column('reference_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_documents', 'reference_type')
    op.drop_column('approval_documents', 'reference_id')
    # ### end Alembic commands ###
