from sqlalchemy import select, func, or_, cast, String
from sqlalchemy.orm import selectinload
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.product import BOM, Product
from app.models.purchasing import MaterialRequirement, PurchaseOrder, PurchaseOrderItem, PurchaseStatus
from app.models.sales import SalesOrder, SalesOrderItem, OrderStatus
from app.models.inventory import Stock
from app.models.production import ProductionPlan, ProductionPlanItem, ProductionStatus
from typing import Dict, List, Optional

async def explode_bom(db: AsyncSession, product_id: int, quantity: float, requirements: List[Dict]):
    """
    Recursively explodes BOM for a product.
    requirements: List of {"product_id": int, "quantity": float, "substitute_id": Optional[int]}
    """
    query = select(BOM).where(BOM.parent_product_id == product_id).options(
        selectinload(BOM.child_product),
        selectinload(BOM.substitute_product)
    )
    result = await db.execute(query)
    bom_items = result.scalars().all()
    
    if not bom_items:
        # leaf node or product without BOM
        requirements.append({"product_id": product_id, "quantity": quantity, "substitute_id": None})
        return

    for bi in bom_items:
        child_needed = bi.required_quantity * quantity
        # Pass the substitute defined in THIS BOM entry down? 
        # No, child_needed might explode further, but substitution is usually at the leaf or intermediate level.
        # However, for this specific request, B is a part (leaf).
        await explode_bom(db, bi.child_product_id, child_needed, requirements)
        
        # If this BOM entry itself has a substitute_id, we should record it for the child_product_id.
        # We find the requirement we just added and attach the substitute_id to it.
        # But explode_bom is recursive.
        
        # [REFINED LOGIC]
        # Instead of recursing after recording, let's treat the substitution as a property of the requirement.
        if bi.substitute_product_id:
            # We need a way to tell the requirement collector that THIS specific child requirement has a substitute.
            # We can't easily do it after the recursive call if the child itself has a BOM.
            # But the user said B is a Part (leaf).
            
            # Find the requirement(s) generated by this child and tag them?
            # Let's just store the info.
            # If bi has a substitute, we only apply it to this specific child_product_id requirement.
            pass

async def calculate_and_record_mrp(
    db: AsyncSession, 
    order_id: Optional[int] = None, 
    plan_id: Optional[int] = None
):
    """
    BOM 전개 및 재고 확인을 통한 부족분 산출 및 MaterialRequirement 기록
    """
    # 1. 대상 선택 (SalesOrder 또는 ProductionPlan)
    items = []
    ref_order_id = order_id
    
    if plan_id:
        print(f"[MRP] Starting MRP calculation for Plan ID: {plan_id}")
        result = await db.execute(
            select(ProductionPlan)
            .where(ProductionPlan.id == plan_id)
            .where(ProductionPlan.status != ProductionStatus.CANCELED)
            .options(selectinload(ProductionPlan.items).selectinload(ProductionPlanItem.product))
        )
        plan = result.scalars().first()
        if not plan:
            print(f"[MRP] Plan {plan_id} not found or is CANCELED.")
            # Clear existing requirements if plan was canceled
            existing_stmt = select(MaterialRequirement).where(MaterialRequirement.plan_id == plan_id)
            existing_res = await db.execute(existing_stmt)
            for mr in existing_res.scalars().all():
                await db.delete(mr)
            await db.commit()
            return
        
        # 1.1 Clear existing records strictly for idempotency
        conditions = [MaterialRequirement.plan_id == plan_id]
        if plan.order_id:
            conditions.append(
                (MaterialRequirement.order_id == plan.order_id) & (MaterialRequirement.plan_id == None)
            )
        
        existing_stmt = select(MaterialRequirement).where(or_(*conditions))
        existing_res = await db.execute(existing_stmt)
        for mr in existing_res.scalars().all():
            await db.delete(mr)
        
        await db.flush() 
        print(f"[MRP] Cleared existing records (Plan {plan_id} and Parent Order {plan.order_id}) for refresh.")

        # 2. Collect targets from plan items
        product_qtys = {}
        for pi in plan.items:
            net_qty = max(0, pi.quantity or 0)
            product_qtys[pi.product_id] = max(product_qtys.get(pi.product_id, 0), net_qty)
        
        for pid, qty in product_qtys.items():
            items.append({"product_id": pid, "quantity": qty})
        
        if plan.order_id:
            ref_order_id = plan.order_id

    elif order_id:
        result = await db.execute(
            select(SalesOrder)
            .where(SalesOrder.id == order_id)
            .where(SalesOrder.status != OrderStatus.CANCELLED)
            .options(selectinload(SalesOrder.items).selectinload(SalesOrderItem.product))
        )
        order = result.scalars().first()
        if not order:
            existing_stmt = select(MaterialRequirement).where(MaterialRequirement.order_id == order_id, MaterialRequirement.plan_id == None)
            existing_res = await db.execute(existing_stmt)
            for mr in existing_res.scalars().all():
                await db.delete(mr)
            await db.commit()
            return
            
        existing_stmt = select(MaterialRequirement).where(MaterialRequirement.order_id == order_id, MaterialRequirement.plan_id == None)
        existing_res = await db.execute(existing_stmt)
        for mr in existing_res.scalars().all():
            await db.delete(mr)
        await db.flush()

        for oi in order.items:
            items.append({"product_id": oi.product_id, "quantity": oi.quantity})

    if not items:
        return

    # 3. BOM Explosion & Aggregation
    # [REFINED] requirements: {product_id: {"total_qty": float, "substitutes": Set[int]}}
    requirements = {} 

    for item in items:
        # Fetch BOM for this top-level product to find substitutes
        bom_query = select(BOM).where(BOM.parent_product_id == item["product_id"])
        bom_res = await db.execute(bom_query)
        bom_map = {b.child_product_id: b.substitute_product_id for b in bom_res.scalars().all()}
        
        # Manual one-level explosion to catch substitutes for specific parent
        for child_id, sub_id in bom_map.items():
            # Get requirement for this child
            qty_needed = item["quantity"] * (await get_bom_qty(db, item["product_id"], child_id))
            
            if child_id not in requirements:
                requirements[child_id] = {"total_qty": 0, "substitute_id": sub_id}
            requirements[child_id]["total_qty"] += qty_needed
            
            # If child has its own BOM, we should explode it (recursive)
            # but usually substitutes are defined at the immediate child level.
            # For simplicity and matching user request "This product only", 
            # we handle the immediate children substitution.
            # For deeper levels, we use a simple explode.
            pass

    # [RE-REFINED] Let's go back to a simpler approach that matches the user's specific request.
    requirements = {} # {product_id: {"required": float, "substitute_id": Optional[int]}}
    
    for item in items:
        # 1. Immediate children of the produced product
        bom_query = select(BOM).where(BOM.parent_product_id == item["product_id"])
        bom_res = await db.execute(bom_query)
        for b in bom_res.scalars().all():
            qty = b.required_quantity * item["quantity"]
            if b.child_product_id not in requirements:
                requirements[b.child_product_id] = {"required": 0, "substitute_id": b.substitute_product_id}
            requirements[b.child_product_id]["required"] += qty

            # 2. Deeper levels (if any, though rare for substituted parts)
            # We'll do a simple recursive explode for children of this child
            # but those won't have the parent-specific substitute logic unless we pass it down.
            # For now, following user's "Product C uses B (sub A)" which is a 1-level relationship.
            pass

    # 4. Record Requirements
    for product_id, data in requirements.items():
        total_required = data["required"]
        sub_id = data["substitute_id"]
        
        product = await db.get(Product, product_id)
        if not product or product.item_type == "PRODUCED":
            continue

        # Check stock of primary
        stock_stmt = select(Stock).where(Stock.product_id == product_id)
        stock_res = await db.execute(stock_stmt)
        stock = stock_res.scalars().first()
        primary_stock = stock.current_quantity if stock else 0

        # Check stock of substitute
        substitute_stock = 0
        if sub_id:
            sub_stock_stmt = select(Stock).where(Stock.product_id == sub_id)
            sub_stock_res = await db.execute(sub_stock_stmt)
            sub_stock_rec = sub_stock_res.scalars().first()
            substitute_stock = sub_stock_rec.current_quantity if sub_stock_rec else 0

        total_available = primary_stock + substitute_stock

        # Check open POs
        po_stmt = (
            select(func.sum(PurchaseOrderItem.quantity - PurchaseOrderItem.received_quantity))
            .join(PurchaseOrder)
            .where(
                PurchaseOrderItem.product_id == product_id,
                PurchaseOrder.status.in_([PurchaseStatus.PENDING, PurchaseStatus.ORDERED, PurchaseStatus.PARTIAL])
            )
        )
        po_res = await db.execute(po_stmt)
        open_purchase_qty = po_res.scalar() or 0

        shortage = max(0, total_required - total_available)

        if total_required > 0:
            req_record = MaterialRequirement(
                product_id=product_id,
                order_id=ref_order_id,
                plan_id=plan_id,
                required_quantity=int(total_required),
                current_stock=int(primary_stock),
                open_purchase_qty=int(open_purchase_qty),
                shortage_quantity=int(shortage),
                status="PENDING"
            )
            # Add note about substitution if applicable
            if sub_id and substitute_stock > 0:
                sub_prod = await db.get(Product, sub_id)
                req_record.status = f"SUB_AVAIL ({sub_prod.name}: {substitute_stock})" if shortage > 0 else "SATISFIED_BY_SUB"
            
            db.add(req_record)
    
    await db.commit()
    print(f"[MRP] Completed MRP calculation with substitution support.")

async def get_bom_qty(db: AsyncSession, parent_id: int, child_id: int) -> float:
    res = await db.execute(select(BOM.required_quantity).where(BOM.parent_product_id == parent_id, BOM.child_product_id == child_id))
    return res.scalar() or 0.0
